name: simple_notes_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  bloc_presentation: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  go_router: ^14.3.0
  hive: ^2.2.3
  hive_generator: ^2.0.1
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  uuid: ^4.5.1


dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.6.8
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  lint: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

